Automated synchronization of Github workflows

diff --git a/.github/workflows/github.yml b/.github/workflows/github.yml
--- a/.github/workflows/github.yml
+++ b/.github/workflows/github.yml
@@ -1,4 +1,4 @@
-name: JSON CI
+name: VCMI Mod CI
 on:
   push:
     branches:
@@ -7,6 +7,108 @@ on:
   workflow_dispatch:
 
 jobs:
+  validate-startup:
+    name: Test VCMI Startup
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    outputs:
+      translations_present: ${{ steps.check.outputs.translations_present }}
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Detect VCMI Version
+        run: |
+          BRANCH="${GITHUB_BASE_REF:-$GITHUB_REF_NAME}"
+          if [[ "$BRANCH" =~ ^vcmi-1\.[0-9]+(-.*)?$ ]]; then
+            echo "VCMI_VERSION=$BRANCH" >> $GITHUB_ENV
+          fi
+
+      - name: Add VCMI PPA Repository
+        if: env.VCMI_VERSION != ''
+        run: sudo add-apt-repository ppa:vcmi/vcmi-latest
+
+      - name: Update Repository
+        if: env.VCMI_VERSION != ''
+        run: sudo apt update
+
+      - name: Install VCMI
+        if: env.VCMI_VERSION != ''
+        run: sudo apt install ${{ env.VCMI_VERSION }}
+
+      - name: Install H3 Data Placeholder
+        if: env.VCMI_VERSION != ''
+        run: |
+          data_url="https://github.com/vcmi-mods/vcmi-test-data/releases/download/v2.0/heroes3.7z"
+          wget "$data_url" -O heroes3.7z
+          mkdir -p ~/.local/share/vcmi/Mods
+          mkdir -p ~/.config/vcmi
+          7za x -o"$HOME/.local/share/vcmi/" heroes3.7z
+
+      - name: Extract Mod Name
+        if: env.VCMI_VERSION != ''
+        run: |
+          MOD_NAME=$(basename ${{ github.repository }})
+          # Hota mod name differs from repository name. Compensate
+          if [[ "${{ github.repository }}" == *"horn-of-the-abyss"* ]]; then
+            MOD_NAME="hota"
+          fi
+          echo "MOD_NAME=${MOD_NAME}" >> $GITHUB_ENV
+
+      - name: Install Mod
+        if: env.VCMI_VERSION != ''
+        run: |
+          ln -sf "$(pwd)" ~/.local/share/vcmi/Mods/${MOD_NAME}
+
+      - name: Install jstyleson
+        run: pip install jstyleson
+
+      - name: Install Mod Dependencies
+        if: env.VCMI_VERSION != ''
+        run: python3 .github/install_mod_dependencies.py "${VCMI_VERSION}"
+
+      - name: Export translations
+        if: env.VCMI_VERSION != ''
+        run: |
+          if ! jq -e '.modType == "Translation"' mod.json >/dev/null; then
+            echo '{ "activePreset" : "default", "presets" : { "default" : { "mods" : [ "vcmi", "core", "' ${MOD_NAME} '" ]}}}' >~/.config/vcmi/modSettings.json
+            vcmiserver --translate-mod=${MOD_NAME}
+          fi
+
+      - name: Check translations folder
+        id: check
+        if: env.VCMI_VERSION != ''
+        run: |
+          DIR="$HOME/.cache/vcmi/extracted/translationFull/${{ env.MOD_NAME }}/"
+          if [ -d "$DIR" ] && [ "$(ls -A "$DIR")" ]; then
+            echo "translations_present=true" >> $GITHUB_OUTPUT
+          else
+            echo "translations_present=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Upload Translation Files
+        if: steps.check.outputs.translations_present == 'true'
+        uses: actions/upload-artifact@v4
+        with:
+          name: translation-export
+          path: ~/.cache/vcmi/extracted/translationFull/${{ env.MOD_NAME }}/
+          retention-days: 1
+
+      - name: Run VCMI
+        if: env.VCMI_VERSION != ''
+        run: |
+          echo '{ "activePreset" : "default", "presets" : { "default" : { "mods" : [ "vcmi", "core", "' ${MOD_NAME} '" ]}}}' >~/.config/vcmi/modSettings.json
+          vcmiserver --dummy-run 2> >(tee error.log)
+          if [ ! -s error.log ]; then
+              echo "Validation OK!"
+              exit 0
+          else
+              echo "Validation failed!"
+              exit 1
+          fi
+
   validate-json:
     name: Validate JSON
     runs-on: ubuntu-latest
@@ -19,6 +121,9 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Update repository
+        run: sudo apt update
+
       - name: Install jstyleson
         run: sudo apt install python3-jstyleson
 
@@ -28,7 +133,7 @@ jobs:
 
   format-json:
     name: Format JSON
-    needs: validate-json
+    needs: [validate-json, validate-startup]
     if: ${{ needs.validate-json.result == 'success' && github.event_name != 'pull_request' }}
     runs-on: ubuntu-latest
     defaults:
@@ -42,9 +147,23 @@ jobs:
         run: |
           npm install -g prettier
 
+      - name: Download translation artifacts
+        if: needs.validate-startup.outputs.translations_present == 'true'
+        uses: actions/download-artifact@v4
+        with:
+          name: translation-export
+          path: ./translation-export
+
+      - name: Refresh translation files
+        if: needs.validate-startup.outputs.translations_present == 'true'
+        run: |
+          mv translation-export ..
+          find . -name english.json -delete
+          python3 .github/merge_dirs.py ../translation-export .
+
       - name: Format JSON files with Prettier
         run: |
-          prettier --write "**/*.json" \
+          prettier --write "**/*.json" "!**/translation/**" \
                    --parser jsonc \
                    --use-tabs \
                    --tab-width 4 \
@@ -60,3 +179,69 @@ jobs:
           default_author: github_actions
           message: "Auto-format JSON files"
           add: '*.json'
+
+  package-artifact:
+    name: Create release
+    needs: [validate-json, format-json]
+    if: >-
+      ${{
+        needs.validate-json.result == 'success' &&
+        github.event_name != 'pull_request' &&
+        github.repository_owner == 'vcmi-mods' &&
+        startsWith(github.ref_name, 'vcmi-')
+      }}
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.sha }}
+          fetch-depth: 0
+
+      - name: Prepare content ZIPs
+        run: bash .github/create_content_zip.sh
+
+      - name: Package release archive
+        run: bash .github/create_release_package.sh
+
+      - name: Strip vcmi- prefix for TAG
+        run: echo "RELEASE_TAG=${GITHUB_REF_NAME#vcmi-}" >> $GITHUB_ENV
+
+      - name: Move tag to current commit
+        run: |
+          git config user.name github-actions
+          git config user.email github-actions@github.com
+
+          git tag -f "${RELEASE_TAG}" "${GITHUB_SHA}"
+          git push origin "${RELEASE_TAG}" --force
+
+      - name: Upload Mod Release Package
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ env.RELEASE_TAG }}     # 1.7, 1.8 etc.
+          name: ${{ github.ref_name }}
+          body: |
+            Automated build for branch `${{ github.ref_name }}`.
+            Commit: `${{ github.sha }}`
+          artifacts: dist/${{ github.event.repository.name }}-${{ github.ref_name }}.zip
+          allowUpdates: true
+          replacesArtifacts: true
+          makeLatest: false
+          commit: ${{ github.sha }}
+
+      # Upload mod.json after Release Package is uploaded to correctly notify end users
+      - name: Upload mod.json
+        uses: ncipollo/release-action@v1
+        with:
+          tag: ${{ env.RELEASE_TAG }}     # 1.7, 1.8 etc.
+          name: ${{ github.ref_name }}
+          artifacts: mod.json
+          allowUpdates: true
+          replacesArtifacts: true
+          makeLatest: false
+          commit: ${{ github.sha }}
